### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by weru88097** [drumpt/SGEM#1]
This error keeps showing up when I call the get_optimizer function, please answer. Thanks!
Below are the specific error codes:
Traceback (most recent call last):
  File "main.py", line 208, in main
    optimizer, scheduler = get_optimizer(args, params, opt_name=args.optimizer, lr=args.lr, scheduler=args.scheduler)
  File "/newdisk0630/wbb/Project/SGEM/utils.py", line 181, in get_optimizer
    optimizer = opt(params, lr=lr, weight_decay=weight_decay)
  File "/home/weiyangjie/anaconda3/envs/sgem/lib/python3.7/site-packages/torch/optim/adamw.py", line 74, in __init__
    super(AdamW, self).__init__(params, defaults)
  File "/home/weiyangjie/anaconda3/envs/sgem/lib/python3.7/site-packages/torch/optim/optimizer.py", line 47, in __init__
    param_groups = list(params)
TypeError: 'NoneType' object is not iterable

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by drumpt** [comment]
Hello,

For that case, you should check whether **collect_params function can collect model parameters appropriately**. In doing so, it might be helpful whether **collect_params function calls another subroutine** (we only support collect_params_{ctc|attn|conf|trans}, and in other architectures you should define your own collect_params_{etc}). Also it might be helpful to check **train_params configuration in conf/config.yaml**.

Thanks in advance,
Changhun Kim

**Comment by weru88097** [comment]
Hi, thank you very much for your reply, after this I had this problem again:
Traceback (most recent call last):
  File "main.py", line 208, in main
    optimizer, scheduler = get_optimizer(args, params, opt_name=args.optimizer, lr=args.lr, scheduler=args.scheduler)
  File "/newdisk0630/wbb/Project/SGEM/utils.py", line 183, in get_optimizer
    return optimizer, eval(scheduler)(optimizer, T_max=args.t_max, eta_min=args.lr_min)
UnboundLocalError: local variable 'optimizer' referenced before assignment

**Comment by drumpt** [comment]
The error indicates that the variable "optimizer" is not properly initialized. Please check that the part 

```
    if opt_name == 'Adam':
        optimizer = opt(params, lr=lr, betas=(beta, 0.999), weight_decay=weight_decay)
    else: 
        optimizer = opt(params, lr=lr, weight_decay=weight_decay)
```

in get_optimizer function works properly.
